
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 22515
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  app:
    build: .
    volumes:
      - .:/app
      - ./documents:/app/documents
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    networks:
      - app-network
    command: sh -c "alembic -c /app/alembic.ini upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  celery-worker:
    build: .
    command: celery -A app.main.celery worker --loglevel=info
    volumes:
      - .:/app
      - ./documents:/app/documents
    depends_on:
      - db
      - rabbitmq
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge