# Generated by Django 5.2.4 on 2025-07-11 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к документу')),
                ('size', models.FloatField(null=True, verbose_name='Размер файла (кб')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('file_type', models.CharField(blank=True, max_length=10, verbose_name='Тип файла')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10, verbose_name='Тип файла')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Цена за кб')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Стоимость заказа')),
                ('payment', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_tesseract.docs', verbose_name='Документ')),
            ],
        ),
        migrations.CreateModel(
            name='UserToDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_tesseract.docs')),
            ],
        ),
    ]
