# Generated by Django 5.2.4 on 2025-07-13 14:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('fastapi_id', models.IntegerField(unique=True, verbose_name='ID в FastAPI')),
                ('fastapi_filepath', models.CharField(max_length=255, verbose_name='Путь в FastAPI')),
                ('size', models.FloatField(verbose_name='Размер (КБ)')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('file_type', models.CharField(blank=True, max_length=10, verbose_name='Тип файла')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10, verbose_name='Тип файла')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Цена за КБ')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Стоимость заказа')),
                ('payment', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_tesseract.docs', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='UserToDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_tesseract.docs', verbose_name='Документ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Связь пользователь-документ',
                'verbose_name_plural': 'Связи пользователь-документ',
            },
        ),
    ]
