# Generated by Django 5.2.4 on 2025-07-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tesseract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
