# Generated by Django 5.2.4 on 2025-07-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tesseract', '0002_docs_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docs',
            options={'ordering': ['-uploaded_at'], 'permissions': [('delete_document', 'Can delete document')], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AddField(
            model_name='docs',
            name='fastapi_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docs',
            name='size',
            field=models.FloatField(null=True, verbose_name='Размер файла (кб)'),
        ),
    ]
