# Generated by Django 5.2.4 on 2025-07-12 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tesseract', '0003_alter_docs_options_docs_fastapi_id_alter_docs_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docs',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='docs',
            name='file_type',
        ),
        migrations.AddField(
            model_name='docs',
            name='fastapi_filepath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='docs',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='docs',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docs',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
