# Generated by Django 5.2.4 on 2025-07-12 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tesseract', '0004_alter_docs_options_remove_docs_file_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='fastapi_filepath',
        ),
        migrations.RemoveField(
            model_name='docs',
            name='fastapi_id',
        ),
        migrations.AddField(
            model_name='docs',
            name='external_doc_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='docs',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
